# Generated by Django 2.2.4 on 2019-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetooneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maried',
            field=models.BooleanField(default=True),
        ),
    ]
