# Generated by Django 2.2.4 on 2019-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetooneapp', '0002_profile_maried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(help_text='enter designation', max_length=64),
        ),
    ]
