# Generated by Django 2.2.4 on 2019-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetooneapp', '0003_auto_20190910_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(max_length=64),
        ),
    ]
