# Generated by Django 2.2.4 on 2019-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetooneapp', '0004_auto_20190914_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
