# Generated by Django 2.2.4 on 2019-09-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetooneapp', '0005_auto_20190914_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='maried',
        ),
    ]
